version: "3.3"
services:
  chrome:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"

  script:
    build: .
    depends_on:
      - chrome
    volumes:
      - .:/script
    links:
      - "chrome:chrome"
    environment:
      - SOCRATA_APP_TOKEN
      - PRIVATE_KEY_ID
      - PRIVATE_KEY
      - CLIENT_EMAIL
      - CLIENT_ID
      - CLIENT_X509_CERT_URL
