version: "3.6"
services:
  firefox:
    image: selenium/standalone-firefox
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"

  script:
    build: .
    depends_on:
      - firefox
    volumes: 
      - .:/script
    command: ["pipenv", "run", "get_data_docker"]
